### ISSUE TITLE
HAL elemento Embedded

### ISSUE THREAD

**Issue by nba1992** [isel-leic-daw/1415v-public#3]
Bom dia. Tenho uma dúvida relativamente à utilização do elemento embedded.

No nosso diagrama de estados da API, a representação de lista de Workitem(s) em HAL pressupõem um elemento embedded, responsável por identificar todos os items workitem.
Ora, o item Workitem, possui uma lista de tipos "co-autores".

A minha dúvida consiste em perceber como vou representar em HAL esses co-autores. Serão representados como "estado" de workitem ou como um "embedded resource".

É possível ter embedded resources dentro de embedded resources?!

Espero ter sido minimamente explicito.

Obrigado,
Nuno Boa-Alma

**Comment by cguedes** [comment]
Sim, da mesma forma que os embedded resources podem ter links (_links), também podem ter embedded resources. Dira que na maior parte das vezes não se deve fazer isso, mas pode ser feito.

Também devem ter em conta que podem listar nos embedded resources esses recursos (i.e.  os co-autores) directamente na primeira lista.

Referência: http://stateless.co/hal_specification.html
